package com.ruoyi.dts.mapper;

import com.ruoyi.dts.domain.DtsGoodsAttribute;
import com.ruoyi.dts.domain.DtsGoodsAttributeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DtsGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(DtsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(DtsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    int insert(DtsGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(DtsGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsGoodsAttribute selectOneByExample(DtsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsGoodsAttribute selectOneByExampleSelective(@Param("example") DtsGoodsAttributeExample example, @Param("selective") DtsGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsGoodsAttribute> selectByExampleSelective(@Param("example") DtsGoodsAttributeExample example, @Param("selective") DtsGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    List<DtsGoodsAttribute> selectByExample(DtsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    DtsGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsGoodsAttribute record, @Param("example") DtsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsGoodsAttribute record, @Param("example") DtsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DtsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}